Added Stripe serivices for retrieveing all subscriptions, last 10 sub…
InternAcademy/CookingApp pull request #76
Opened 2024-07-08 11:04 UTC by ChrisIvanov

Added Stripe services for retrieving all subscriptions, last 10 subscriptions, subscribed/canceled ratio and last 30 day profits.

Added 3 view models for CustomerData, IncomeStatistics and SubscriptionStatistics. 

Added StripeController endpoints to connect with those services and display the necessary data.

2024-07-08 11:40 UTC, ImSk1 requested changes
![image](https://github.com/InternAcademy/CookingApp/assets/92582019/84287239-2b71-4987-a7f5-bcae0cbff327)
![image](https://github.com/InternAcademy/CookingApp/assets/92582019/03432818-8c0a-4c5f-bc69-71ee2b39bb6e)
Не ползваме try catch имаме Ex Handler middleware който е с идеята да обработва throw-нати грешки. Трябва да се throw-ват смислени custom грешки, който да могат логично да се обърнат към статус кодове при нужда.

Console.WriteLine не е ок, имаме logger за тази цел.

Ако е крайно наложително да се ползва try catch поне да е за специфична грешка, а не за универсална.

2024-07-08 11:42 UTC, ImSk1 commented
![image](https://github.com/InternAcademy/CookingApp/assets/92582019/9e607af2-042f-4dbd-b815-49881f1ba6d9)


= default!; на всички non nullable string properties в ViewModels за да не дават warning-и github и IDE-то

2024-07-08 11:42 UTC, Ekrem05 commented
1. Всички пропъртита на viewmodel-ите от тип string е добре да са non-nullable със стойнст empty или !default. Тоест 
![image](https://github.com/InternAcademy/CookingApp/assets/78847462/52f2443f-b689-4960-a8ea-6bfc16513a48)
или 
![image](https://github.com/InternAcademy/CookingApp/assets/78847462/c76501c7-2456-4307-b03b-121f2256625d)
2.

2024-07-08 11:48 UTC, Ekrem05 commented
![image](https://github.com/InternAcademy/CookingApp/assets/78847462/5ee97ede-70cb-4c26-99fd-eff4e0609c26)
Този сървиз трябва да го вкараш от Inversion of contoll контейнера в ServiceCollectionExtension.cs и най - долу са Stripe сървисите
![image](https://github.com/InternAcademy/CookingApp/assets/78847462/a438b79d-4338-4409-9457-2317a7c54fdd)

2024-07-09 07:47 UTC, ImSk1 approved these changes

2024-07-09 07:48 UTC, merged